@Restaurants.API_HostAddress = https://localhost:7100
@domain=http://localhost
@port =5100
@Restaurants_HostAddress = https://localhost:7100

###
POST {{Restaurants_HostAddress}}/api/weatherforecast/generate?maxResult=4
Content-Type: application/json

{
  "MinTemperature": -3,
  "MaxTemperature": 28
}


###

GET {{Restaurants.API_HostAddress}}/api/restaurants

###
