@Restaurants.API_HostAddress = https://localhost:7100
@domain=http://localhost
@port =5100
@Restaurants_HostAddress = https://localhost:7100

###
POST {{Restaurants_HostAddress}}/api/weatherforecast/generate?maxResult=4
Content-Type: application/json

{
  "MinTemperature": -3,
  "MaxTemperature": 28
}


###

GET {{Restaurants.API_HostAddress}}/api/restaurants

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/2

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/10

###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Content-Type: application/json

{
  "Name": "KFC @Junction10",
  "Description": "Famous fast-food chain known for fried chicken",
  "Category": "Fast Food",
  "HasDelivery": true,
  "ContactEmail": "contact@kfcjunction10.com",
  "ContactNumber": "+65-6123-4567",
  "City": "Singapore",
  "Street": "123 Bukit Panjang Road",
  "PostalCode": "238838"
}

###
